In [3]:
import numpy as np
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [11]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [13]:
np.linspace(10,100,4)

array([ 10.,  40.,  70., 100.])

In [14]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [17]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [18]:
np.random.rand(2,3)

array([[0.63135   , 0.88041737, 0.45930593],
       [0.33296761, 0.5388023 , 0.92690883]])

In [20]:
arr=np.random.randn(2,4)
arr

array([[-0.23141019, -0.62285015,  0.49211243, -0.09647815],
       [-0.54590405,  1.22802435,  0.09578975, -0.2216066 ]])

In [23]:
np.random.randint(2,100)

38

In [24]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [26]:
rand_array=np.random.randint(0,10,50)
rand_array

array([0, 3, 8, 0, 1, 0, 6, 8, 7, 3, 6, 5, 6, 2, 6, 4, 4, 3, 5, 0, 7, 8,
       5, 3, 3, 9, 5, 5, 1, 8, 0, 1, 0, 0, 3, 2, 6, 7, 5, 8, 9, 0, 5, 1,
       7, 9, 2, 5, 0, 3])

In [27]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [28]:
sample_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [29]:
rand_array.max()

9

In [30]:
rand_array.argmax()

25

In [31]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [1]:
type("ai")

str

In [2]:
x=10
type(x)

int

In [3]:
y=True
type(y)

bool

In [4]:
y="true"
type(y)

str

#### list

#### 1] container object
#### 2]heterogenous->allows multiple data types
#### 3]can have duplicates
#### 4]immutable->cannot make changes
#### 5]elements are separated by comma, enclosed in paranthesis or without any brackets 

In [ ]:
sample_list=[1,2,3,7,-1,"hi",5.7,1,1,1]
sample_list

In [9]:
sample_list[4]

-1

In [7]:
sample_list[0]

1

In [11]:
sample_list[10]

IndexError: list index out of range

In [12]:
sample_list[4]=12
sample_list

[1, 2, 3, 7, 12, 'hi', 5.7, 1, 1, 1]

In [13]:
sample_tuple2=1.6,2.3,8.3,"hi"
sample_tuple2

(1.6, 2.3, 8.3, 'hi')

In [15]:
type(sample_tuple2)

tuple

In [16]:
sample_tuple[0]=15

NameError: name 'sample_tuple' is not defined

### Sets

In [20]:
sample_set={1,2,3,4,5,6,7,"hi","ahelo","zheloe",3.5,73.3,34,35}

In [21]:
sample_set

{1, 2, 3, 3.5, 34, 35, 4, 5, 6, 7, 73.3, 'ahelo', 'hi', 'zheloe'}

In [22]:
sample_set[9]

TypeError: 'set' object is not subscriptable

In [25]:
sample_set.add(100)
sample_set

{1, 100, 2, 3, 3.5, 34, 35, 4, 5, 6, 7, 73.3, 'ahelo', 'hi', 'zheloe'}

In [26]:
sample_set.add(100)

In [27]:
sample_set

{1, 100, 2, 3, 3.5, 34, 35, 4, 5, 6, 7, 73.3, 'ahelo', 'hi', 'zheloe'}

In [30]:
sample_set.remove(1)
sample_set

{100, 2, 3, 3.5, 34, 35, 4, 5, 6, 7, 73.3, 'ahelo', 'hi', 'zheloe'}

### Dictionary

#### 1]key-value pair
#### 2]{}
#### 3]Indexing-Square Bracket
#### 4]Mutable

In [47]:
dict_1={'name':'arun','hobbies':['painting','singing','cooking'],1:23}
dict_1

{'name': 'arun', 'hobbies': ['painting', 'singing', 'cooking'], 1: 23}

In [55]:
dict_1.update({"class":"ds"})
dict_1

{1: 23, 'name': 'likith', 'class': 'ds'}

In [48]:
dict_1.keys()

dict_keys(['name', 'hobbies', 1])

In [34]:
dict_1.values()

dict_values(['arun', ['painting', 'singing', 'cooking'], 23])

In [54]:
dict_1['name']='likith'
dict_1

{1: 23, 'name': 'likith'}

In [50]:
del dict_1['hobbies']

In [51]:
dict_1

{'name': 'likith', 1: 23}

In [52]:
del dict_1['name']

In [53]:
dict_1

{1: 23}

In [56]:
len(dict_1)

3